### ISSUE TITLE
branches

### ISSUE THREAD

**Issue by hzrd149** [waldenn/spirare#14]
iv noticed that every time you make a change/fix some thing you have to merge "master" back into "gh-pages".
id recommend just setting "gp-pages" as the default branch and remove/deleting branch "master"
that way you wont have to merge the branch for ever change :)

also what is "spirare"?
thanks.

**Comment by joppiesaus** [comment]
You have a good point there. But, having two branches is an advantage, since you can have your demo and your work-in-progress separate. Of course, you could have a `dev` branch for that, but you get the idea. At the moment it doesn't matter, since all the commits aren't especially ground-breaking.(@waldenn step it up!!1!)

Spirare is a place for people who don't go to school anymore, because they can't develop their talents there and can't function properly in "normal" society - because they can't be themselves for the previous reason. So they go into an environment where they can do what they want while being accompanied.
This includes learning, getting new work, getting to know yourself. In the end, everyone does something else. Some go to university, some start a company, some start working.

So I'm 16, and I like to program stuff, so they hired a programmer to teach me stuff. Same goes for music, painting, or for some-science-nobody-studies. This isn't possible at high school.

So, the programmer is @waldenn, and he has started this project. It's meant for learning. So, people who come here don't know what git is and they want to learn git too, and if you have all different practices it becomes confusing. Like, when they fork the project, and they can't checkout `master`. I guess that's a good reason, but we didn't think about your idea really.

This may not be 100% accurate, or the whole story(it applies for non-school people aswell, other complex reasons). I don't know what country you live in, so it may be all very confusing, but I hope you get the idea, and keep on doing awesome stuff! :metal:

**Comment by hzrd149** [comment]
good point, its always good to have a dev branch, or in this case the "master" branch.

thanks for clearing that up, before i thought "spirare" was just the name of a github repository that was being worked on by two friends.
but that just goes to show what kinds of awesome stuff you can find on the internet without even realizing it. :smile: 

with regards to what im doing here.
im about your age <i>(+ or - 3 years, id rather not put my exact age here)</i> i live in the US.
im home schooled, and have been programming for the past 4 years.

ps. awesome work on your new site, keep up the good work :+1:
